credentials:
  usernames:
    admin:
      email: admin@email.com
      name: Admin
      password: '123' # Trocar por senha hashed
    user:
      email: user@email.com
      name: Usuário
      password: abc # Trocar por senha hashed
cookie:
  expiry_days: 1
  key: random_signature_key # Deve ser string
  name: random_cookie_name
preauthorized:
  emails:
  - email@email.com